#!/bin/sh
#
# This file is part of VRto3D.
#
# VRto3D is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# VRto3D is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with VRto3D. If not, see <http://www.gnu.org/licenses/>.
#
# Compiles the repack shaders to SPIR-V and wraps them into C headers under
# generated/. The headers are checked in as a toolchain fallback so the build
# only needs a C++ compiler; re-run this script after editing any shader.
#
# Requires: glslc (shaderc), typically from the Vulkan SDK or distro package.

set -eu
cd "$(dirname "$0")"

mkdir -p generated

# emit <input-shader> <symbol-stem>
# Produces generated/<symbol-stem>_spv.h defining:
#     static const uint32_t <symbol-stem>_spv[] = { ... };
# glslc -mfmt=c emits just the {...} initializer list; we wrap it here.
emit() {
    in=$1
    name=$2
    out="generated/${name}_spv.h"
    tmp=$(mktemp)

    glslc -O -mfmt=c "$in" -o "$tmp"

    {
        printf '/*\n'
        printf ' * This file is part of VRto3D.\n'
        printf ' *\n'
        printf ' * VRto3D is free software: you can redistribute it and/or modify\n'
        printf ' * it under the terms of the GNU Lesser General Public License as published by\n'
        printf ' * the Free Software Foundation, either version 3 of the License, or\n'
        printf ' * (at your option) any later version.\n'
        printf ' *\n'
        printf ' * VRto3D is distributed in the hope that it will be useful,\n'
        printf ' * but WITHOUT ANY WARRANTY; without even the implied warranty of\n'
        printf ' * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the\n'
        printf ' * GNU Lesser General Public License for more details.\n'
        printf ' *\n'
        printf ' * You should have received a copy of the GNU Lesser General Public License\n'
        printf ' * along with VRto3D. If not, see <http://www.gnu.org/licenses/>.\n'
        printf ' */\n'
        printf '/* Generated by compile_shaders.sh from %s — do not edit. */\n' "$in"
        printf '#pragma once\n'
        printf '\n'
        printf '#include <stdint.h>\n'
        printf '\n'
        printf 'static const uint32_t %s_spv[] =\n' "$name"
        cat "$tmp"
        printf ';\n'
    } > "$out"

    rm -f "$tmp"
    echo "wrote $out"
}

emit fullscreen.vert fullscreen_vert
emit repack.frag    repack_frag
