name: Update Changelog

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install dependencies (gh + jq)
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

        # Install gh CLI
        type -p curl >/dev/null || sudo apt install curl -y
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | \
          sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] \
          https://cli.github.com/packages stable main" | \
          sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update
        sudo apt install gh -y

    - name: Authenticate GitHub CLI
      run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

    - name: Generate changelog.md from releases
      run: |
        echo "# Changelog" > changelog.md

        for tag in $(gh release list --limit 1000 --json tagName --jq '.[].tagName'); do
          info=$(gh release view "$tag" --json name,publishedAt,body)

          name=$(echo "$info" | jq -r '.name')
          date=$(echo "$info" | jq -r '.publishedAt')
          body=$(echo "$info" | jq -r '.body')

          echo -e "\n## $name ($tag) - $date\n\n$body\n" >> changelog.md
        done

    - name: Commit changelog.md if changed
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

        # if ! git diff --quiet -- changelog.md; then
          git add changelog.md
          git commit -m "Auto-update changelog.md from GitHub releases"
          git push
        # else
          # echo "No changes in changelog.md. Skipping commit."
        # fi